export const melbourne = [
    { name: 'Albert Park', postcode: '3206' },
    { name: 'Docklands', postcode: '3008' },
    { name: 'Melbourne', postcode: '3000' },
    { name: 'Middle Park', postcode: '3206' },
    { name: 'Port Melbourne', postcode: '3207' },
    { name: 'South Melbourne', postcode: '3205' },
    { name: 'South Wharf', postcode: '3006' },
    { name: 'Southbank', postcode: '3006' },
    { name: 'West melbourne', postcode: '3003' },
    { name: 'Armadale', postcode: '3143' },
    { name: 'Balaclava', postcode: '3183' },
    { name: 'Kooyong', postcode: '3144' },
    { name: 'Malvern', postcode: '3144' },
    { name: 'Prahran', postcode: '3181' },
    { name: 'South yarra', postcode: '3141' },
    { name: 'St kilda', postcode: '3182' },
    { name: 'St kilda east', postcode: '3183' },
    { name: 'St kilda west', postcode: '3182' },
    { name: 'Toorak', postcode: '3142' },
    { name: 'Windsor', postcode: '3181' },
    { name: 'Brunswick', postcode: '3056' },
    { name: 'Brunswick West', postcode: '3055' },
    { name: 'Carlton', postcode: '3053' },
    { name: 'Carlton north', postcode: '3054' },
    { name: 'Collingwood', postcode: '3066' },
    { name: 'Fitzroy', postcode: '3065' },
    { name: 'North Melbourne', postcode: '3051' },
    { name: 'Parkville', postcode: '3052' },
    { name: 'Princes Hill', postcode: '3054' },
    { name: 'Essendon', postcode: '3040' },
    { name: 'Essendon North', postcode: '3041' },
    { name: 'Pascoe Vale South', postcode: '3044' },
    { name: 'Coburg', postcode: '3058' },
    { name: 'Strathmore', postcode: '3041' },
    { name: 'Aberfeldie', postcode: '3040' },
    { name: 'Moonee ponds', postcode: '3039' },
    { name: 'Ascot Vale', postcode: '3032' },
    { name: 'Flemington', postcode: '3031' },
    { name: 'Footscray', postcode: '3011' },
    { name: 'Kensington', postcode: '3031' },
    { name: 'Maribyrnong', postcode: '3032' },
    { name: 'Seddon', postcode: '3011' },
    { name: 'Travancore', postcode: '3032' },
    { name: 'Yarraville', postcode: '3013' },
    { name: 'Fitzroy North', postcode: '3068' },
    { name: 'Brunswick East', postcode: '3057' },
    { name: 'Clifton Hill', postcode: '3068' },
    { name: 'Fairfield', postcode: '3078' },
    { name: 'Northcote', postcode: '3070' },
    { name: 'Thornbury', postcode: '3071' },
    { name: 'Preston', postcode: '3072' },
    { name: 'East Melbourne', postcode: '3002' },
    { name: 'Hawthorn', postcode: '3122' },
    { name: 'Hawthorn East', postcode: '3123' },
    { name: 'Kew', postcode: '3101' },
    { name: 'Richmond', postcode: '3121' },
    { name: 'Burnley', postcode: '3121' },
    { name: 'Cremorne', postcode: '3121' },
    { name: 'Abbotsford', postcode: '3067' },
    { name: 'Bentleigh', postcode: '3204' },
    { name: 'Brighton', postcode: '3186' },
    { name: 'Brighton East', postcode: '3187' },
    { name: 'Caulfield', postcode: '3162' },
    { name: 'Caulfield East', postcode: '3145' },
    { name: 'Caulfield North', postcode: '3161' },
    { name: 'Caulfield south', postcode: '3162' },
    { name: 'Elsternwick', postcode: '3185' },
    { name: 'Elwood', postcode: '3184' },
    { name: 'Gardenvale', postcode: '3185' },
    { name: 'Glen Huntly', postcode: '3163' },
    { name: 'McKinnon', postcode: '3204' },
    { name: 'Ormond', postcode: '3204' },
    { name: 'Ripponlea', postcode: '3185' }
];

export const sydney = [
    { name: 'barangaroo', postcode: '2000' },
    { name: 'chippendale', postcode: '2008' },
    { name: 'darlington', postcode: '2008' },
    { name: 'dawes point', postcode: '2000' },
    { name: 'haymarket', postcode: '2000' },
    { name: 'millers point', postcode: '2000' },
    { name: 'pyrmont', postcode: '2009' },
    { name: 'redfern', postcode: '2016' },
    { name: 'St Peters', postcode: '2044' },
    { name: 'surry hills', postcode: '2010' },
    { name: 'sydenham', postcode: '2044' },
    { name: 'sydney', postcode: '2000' },
    { name: 'tempe', postcode: '2044' },
    { name: 'the rocks', postcode: '2000' },
    { name: 'ultimo', postcode: '2007' },
    { name: 'waterloo', postcode: '2017' },
    { name: 'glebe', postcode: '2037' },
    { name: 'zetland', postcode: '2017' },
    { name: 'bellevue hill', postcode: '2023' },
    { name: 'bondi', postcode: '2026' },
    { name: 'bondi beach', postcode: '2026' },
    { name: 'bondi junction', postcode: '2022' },
    { name: 'clovelly', postcode: '2031' },
    { name: 'darling point', postcode: '2027' },
    { name: 'darlinghurst', postcode: '2010' },
    { name: 'double bay', postcode: '2028' },
    { name: 'edgecliff', postcode: '2027' },
    { name: 'elizabeth bay', postcode: '2011' },
    { name: 'north bondi', postcode: '2026' },
    { name: 'paddington', postcode: '2021' },
    { name: 'point piper', postcode: '2027' },
    { name: 'potts point', postcode: '2011' },
    { name: 'rose bay', postcode: '2029' },
    { name: 'rushcutters bay', postcode: '2011' },
    { name: 'tamarama', postcode: '2026' },
    { name: 'Woollahra', postcode: '2025' },
    { name: 'bronte', postcode: '2024' },
    { name: 'centennial park', postcode: '2021' },
    { name: 'moore park', postcode: '2021' },
    { name: 'queens park', postcode: '2022' },
    { name: 'waverley', postcode: '2024' },
    { name: 'woolloomooloo', postcode: '2011' },
    { name: 'ashbury', postcode: '2193' },
    { name: 'Abbotsford', postcode: '2046' },
    { name: 'annandale', postcode: '2038' },
    { name: 'balmain', postcode: '2041' },
    { name: 'balmain east', postcode: '2041' },
    { name: 'birchgrove', postcode: '2041' },
    { name: 'canada bay', postcode: '2046' },
    { name: 'Chiswick', postcode: '2046' },
    { name: 'croydon', postcode: '2132' },
    { name: 'drummoyne', postcode: '2047' },
    { name: 'five dock', postcode: '2046' },
    { name: 'forest lodge', postcode: '2037' },
    { name: 'haberfield', postcode: '2045' },
    { name: 'leichhardt', postcode: '2040' },
    { name: 'lewisham', postcode: '2049' },
    { name: 'lilyfield', postcode: '2040' },
    { name: 'rodd point', postcode: '2046' },
    { name: 'russell lea', postcode: '2046' },
    { name: 'summer hill', postcode: '2130' },
    { name: 'ashfield', postcode: '2131' },
    { name: 'wareemba', postcode: '2046' },
    { name: 'cammeray', postcode: '2062' },
    { name: 'cremorne', postcode: '2090' },
    { name: 'cremorne point', postcode: '2090' },
    { name: 'crows nest', postcode: '2065' },
    { name: 'greenwich', postcode: '2065' },
    { name: 'kirribilli', postcode: '2061' },
    { name: 'kurraba point', postcode: '2089' },
    { name: 'lavender bay', postcode: '2060' },
    { name: 'mcmahons point', postcode: '2060' },
    { name: 'milsons point', postcode: '2061' },
    { name: 'mosman', postcode: '2088' },
    { name: 'neutral bay', postcode: '2089' },
    { name: 'north sydney', postcode: '2060' },
    { name: 'waverton', postcode: '2060' },
    { name: 'wollstonecraft', postcode: '2065' },
    { name: 'artarmon', postcode: '2064' },
    { name: 'castle cove', postcode: '2069' },
    { name: 'castlecrag', postcode: '2068' },
    { name: 'chatswood', postcode: '2067' },
    { name: 'chatswood west', postcode: '2067' },
    { name: 'lane cove', postcode: '2066' },
    { name: 'lane cove north', postcode: '2066' },
    { name: 'lane cove west', postcode: '2066' },
    { name: 'linley point', postcode: '2066' },
    { name: 'longueville', postcode: '2066' },
    { name: 'middle cove', postcode: '2068' },
    { name: 'naremburn', postcode: '2065' },
    { name: 'north willoughby', postcode: '2068' },
    { name: 'northbridge', postcode: '2063' },
    { name: 'northwood', postcode: '2066' },
    { name: 'riverview', postcode: '2066' },
    { name: 'st leonards', postcode: '2065' },
    { name: 'willoughby', postcode: '2068' },
    { name: 'willoughby east', postcode: '2068' },
    { name: 'coogee', postcode: '2034' },
    { name: 'daceyville', postcode: '2032' },
    { name: 'eastgardens', postcode: '2036' },
    { name: 'eastlakes', postcode: '2018' },
    { name: 'kensington', postcode: '2033' },
    { name: 'maroubra', postcode: '2035' },
    { name: 'mascot', postcode: '2015' },
    { name: 'pagewood', postcode: '2035' },
    { name: 'randwick', postcode: '2031' },
    { name: 'south coogee', postcode: '2034' },
    { name: 'botany', postcode: '2019' },
    { name: 'rosebery', postcode: '2018' },
    { name: 'camperdown', postcode: '2050' },
    { name: 'canterbury', postcode: '2193' },
    { name: 'dulwich hill', postcode: '2203' },
    { name: 'earlwood', postcode: '2206' },
    { name: 'enmore', postcode: '2042' },
    { name: 'hurlstone park', postcode: '2193' },
    { name: 'marrickville', postcode: '2204' },
    { name: 'newtown', postcode: '2042' },
    { name: 'alexandria', postcode: '2015' },
    { name: 'beaconsfield', postcode: '2015' },
    { name: 'eveleigh', postcode: '2015' },
    { name: 'petersham', postcode: '2049' },
    { name: 'rozelle', postcode: '2039' },
    { name: 'st peters', postcode: '2044' },
    { name: 'erskineville', postcode: '2043' },
    { name: 'stanmore', postcode: '2048' }
];

export default {
    melbourne,
    sydney
};