export default {
    siteRoot: 'http://localhost:3000',
    authenticationCookie: 'tipple-token',
    existingAuthenticationCookie: 'tpl_session',
    cookieDomain: '.tipple.xyz',
    confirmedAddressCookie: 'tipple-address',
    deviceIdentifierCookie: 'tipple-device-identifier',
    userIdentifierCookie: 'tipple-user-identifier',
    ageVerificationCookie: 'tipple-age-verification',
    insecureCookies: true,
    imageBase: "https://content.tipple.com.au/tipple",
    authenticationURI: 'https://tipple.xyz/api',
    baseURI: 'https://tipple.xyz/api',
    googleApiKey: 'AIzaSyA6ToXBt04qLqUJzjfYuWnfL9pqAMmIgis',
    splitIoAuthorizationKey: 'j6qddmm24op529cgi49h76209nanld0ma3i9',
    splitIoTrafficType: 'user',
    nrLicenseKey: "5849d0b811",
    nrApplicationID: "233991980",
    nrReleaseName: '@@NR_RELEASE_NAME@@',
    nrReleaseId: '@@NR_RELEASE_ID@@',
    segmentKey: "SnAbdJoOW1pfbexM70tTuYgT11jKHfsD",
    liveChatLicense: "7330911",
    enableAnalytics: false,
    defaultStorePath: "/bottleshop/victoria/melbourne",
    defaultStoreId: 34,
    siteId: 1,
    theme: 'tipple.xyz'
}